### PR TITLE
Fix QUERY_WITH_SAME_ID_IS_ALREADY_RUNNING by appending query_id

### LINKED ISSUE #4174: Error: Code: 216. DB::Exception: Query with id = duration_and_count_over_time_hourly-d84101541bb6a is al...
Sentry Issue: [GRAPHQL-HIVE-1C3](https://the-guild-z4.sentry.io/issues/4598460506/?referrer=github_integration)

```
Error: Code: 216. DB::Exception: Query with id = duration_and_count_over_time_hourly-d84101541bb6a is already running. (QUERY_WITH_SAME_ID_IS_ALREADY_RUNNING)
```

### PR DESCRIPTION
**Pull request by kamilkisiela**
Fixes #4174

### CODE REVIEW

File: packages/services/api/src/modules/operations/providers/clickhouse-client.ts [hunk 1]
```diff
@@ -145,6 +147,39 @@ export class ClickHouse {
...
+                // Context: https://clickhouse.com/docs/en/interfaces/http
+                // > Running requests do not stop automatically if the HTTP connection is lost.
+                // > The optional 'query_id' parameter can be passed as the query ID (any string).
+                // More context: https://clickhouse.com/docs/en/operations/settings/settings#replace-running-query
+                // > When using the HTTP interface, the 'query_id' parameter can be passed.
+                // > If a query from the same user with the same 'query_id' already exists at this time,
+                // > the behaviour depends on the 'replace_running_query' parameter.
+                // > Default: throws QUERY_WITH_SAME_ID_IS_ALREADY_RUNNING exception.
+                options.searchParams.query_id = options.searchParams.query_id.replace(
+                  /\-r\d$/,
```
Comment (kamilkisiela) [inline packages/services/api/src/modules/operations/providers/clickhouse-client.ts:171]:
```suggestion
                  /-r\d$/,
```
