### PR TITLE
Date range component: fix sorting and storybook

### LINKED ISSUE #4696: Date range component: fix order in search input

### PR DESCRIPTION
**Pull request by TuvalSimha**
### Background

Date range component sorting was confusing, this PR come to sort the range based on weight.

closes #4696

### CODE REVIEW

File: packages/web/app/src/components/ui/date-range-picker.tsx [hunk 1]
```diff
@@ -273,13 +273,32 @@ export function DateRangePicker(props: DateRangePickerProps): JSX.Element {
   }, [quickRangeFilter, validUnits]);
 
   presets = [...presets, ...dynamicPresets].sort((a, b) => {
-    if (a.label < b.label) {
-      return -1;
+    const aWeight = a.label.includes('minutes')
```
Comment (dotansimha) [inline packages/web/app/src/components/ui/date-range-picker.tsx:276]: hmm, I guess you can move this logic of calculating weight into something else? 

Also, maybe the ideal way to understand the "weight" is to measure how many minutes you have between now and the result date?

For example:
"last 10 minutes" = 10 
"last 2 days" =  2880
